// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';




class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5LSWJ6CycpNVbERRkTHAv0TCa_CV7juY',
    appId: '1:835278701885:android:13da19df59840f80b73154',
    messagingSenderId: '835278701885',
    projectId: 'stevenson-takeo',
    databaseURL: 'https://stevenson-takeo-default-rtdb.firebaseio.com',
    storageBucket: 'stevenson-takeo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXxXdw0rKxDMLZU4FqlY3mvB7YlvrhZ5s',
    appId: '1:835278701885:ios:207c5e280c6ff18db73154',
    messagingSenderId: '835278701885',
    projectId: 'stevenson-takeo',
    databaseURL: 'https://stevenson-takeo-default-rtdb.firebaseio.com',
    storageBucket: 'stevenson-takeo.appspot.com',
    iosClientId: '835278701885-ls09e31toj3iutf1p1qrfskpb4mim0aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.stevensontakeout',
  );
}
